development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://akamoofkobpnov:f8368301608c1bb7673ad0a7fbc729d6dd7ff4b453dbf20f8c193384d04763bc@ec2-50-16-196-57.compute-1.amazonaws.com:5432/d6i99uiu6shsf6
